name: E2E
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'cypress/**'
      - 'src/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    timeout-minutes: 4
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Build pkg
        run: yarn build
      - name: Run tests
        run: yarn ci:e2e
