name: Unit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jest:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Run lint
        run: yarn ci:lint
